# Generated by Django 5.2 on 2025-04-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
